spring:
  application:
    name: telemetry-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: telemetry-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: '*'
      spring.json.use.type.headers: false
      spring.json.value.default.type: ru.yandex.practicum.smarthome.telemetryservice.model.TelemetryDataDTO
  datasource:
    url: jdbc:postgresql://postgres:5432/telemetry_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update